POST http://localhost:8000/api/schedule HTTP/1.1
content-type: application/json

{
	"token": "hc3jCI5QpneRFbZnIIuGf05RKtvkDqpq",
	"deviceId": "3",
	"command": "testCommand2",
	"time": "12:44",
	"info": "300"
}