POST http://localhost:8000/api/schedule HTTP/1.1
content-type: application/json

{
	"token": "kP6pYrqftkIznyF8bbzDa9VdRFoA3K8j",
	"deviceId": "4",
	"command": "testCommand",
	"time": "12:44",
	"info": "300"
}